name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          token: ${{ github.token }}
          repo:  VidSync
          owner:  SimpleIDE-Official
          base: master
          head: master
          merge_method:	merge
          #auto_approve: false
          #auto_merge: true
